clean start

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -4,6 +4,7 @@ on:
   push:
     branches:
       - master
+
 jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
@@ -23,11 +24,45 @@ jobs:
         with:
           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
 
+      - name: Check for build-related changes on server
+        id: check_changes
+        run: |
+          ssh -o StrictHostKeyChecking=no "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "[[ -f /var/www/fc.io/deploy/last_deployed_commit ]] && echo 'yes' || echo 'no'" > last_deployed_commit.txt
+
+          if [ -f last_deployed_commit.txt ]; then
+            if grep -q "yes" last_deployed_commit.txt; then
+              ssh -o StrictHostKeyChecking=no "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "
+                cd /var/www/fc.io
+                git fetch origin master
+                LAST_DEPLOYED_COMMIT=$(cat deploy/last_deployed_commit)
+                if git diff --name-only "$LAST_DEPLOYED_COMMIT" origin/master | grep -E '(docker-compose.yml|^docker/)'; then
+                  echo "true" > /tmp/build_required.txt
+                else
+                  echo "false" > /tmp/build_required.txt
+                fi
+              "
+            else
+              ssh -o StrictHostKeyChecking=no "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "echo 'true' > /tmp/build_required.txt"
+            fi
+          fi
+
+          BUILD_REQUIRED=$(ssh -o StrictHostKeyChecking=no "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "cat /tmp/build_required.txt")
+          echo "build_required=$BUILD_REQUIRED" >> $GITHUB_ENV
+
       - name: Deploy to server using Docker Compose
         run: |
-          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
-            cd /var/www
-            git pull
-            docker-compose down
-            docker-compose up --build -d
-          EOF
+          ssh -o StrictHostKeyChecking=no "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "
+            cd /var/www/fc.io
+            git pull --rebase
+
+            if [[ "${{ env.build_required }}" == "true" ]]; then
+              echo "Build-related changes detected. Rebuilding containers."
+              docker compose down
+              docker compose up --build -d
+            else
+              echo "No build-related changes detected. Starting existing containers."
+              docker compose up -d
+            fi
+
+            git rev-parse HEAD > deploy/last_deployed_commit
+          "
